format = """
[╭─░▒▓](fg:#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$gradle\
$haskell\
$java\
$rust\
[](fg:#86BBD8 bg:#33658A)\
$time\
[ ](fg:#33658A)\
[\n╰─ ](fg:#9A348E)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# better characters
[character]
success_symbol = '[](bold green)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"documents" = " "
"Downloads" = " "
"music" = " "
"pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ via $symbol]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ via $symbol ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ via $symbol ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ via $symbol ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ via $symbol ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ via $symbol ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'
