[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5b6268"
blue = "#2257a0"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#00cc00"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#abb2bf"
yellow = "#da8548"

[colors.primary]
background = "#000000"
foreground = "#bbc2cf"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 12

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mode = "~Alt"
mods = "Shift|Control"

[scrolling]
history = 10000
multiplier = 2

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.6
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
